# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество билетов'),
        ),
    ]
