# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170903_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Идентификатор чата промоутера'),
        ),
    ]
