# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170903_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='count_came',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пришло человек'),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_came',
            field=models.BooleanField(default=False, verbose_name='Присутсвовал'),
        ),
    ]
