# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170905_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
