# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_guest_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('active', models.BooleanField(verbose_name='Текущее')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Event', verbose_name='Мероприятие'),
        ),
    ]
